import SwiftUI
import AppKit

/// App-owned text updates immediately; native macOS dialogs follow the OS language.
enum ReaderLanguage {
    static func resolve(_ selection: String, preferred: [String] = Locale.preferredLanguages) -> String {
        if ["en", "es"].contains(selection) { return selection }
        return preferred.first(where: {
            let code = $0.lowercased().split(whereSeparator: { $0 == "-" || $0 == "_" }).first
            return code == "en" || code == "es"
        }).map { $0.lowercased().hasPrefix("es") ? "es" : "en" } ?? "en"
    }
    static func text(_ key: String, language: String) -> String {
        language == "es" ? key : english[key] ?? key
    }
    static let english: [String: String] = [
        "Texto pegado": "Pasted Text",
        "Pegar Markdown": "Paste Markdown",
        "Nueva nota": "New note",
        "Crear nota": "Create Note",
        "Guardar Markdown": "Save Markdown",
        "Escribir": "Write",
        "Vista previa": "Preview",
        "Título": "Heading",
        "Subtítulo": "Subheading",
        "Negrita": "Bold",
        "Lista": "List",
        "Tabla": "Table",
        "No se pudo guardar": "Unable to save",
        "Suelta un Markdown aquí": "Drop a Markdown file here",
        "o crea una nota nueva": "or create a new note",
        "Lectura local": "Local reading",
        "Acerca de MD Lite": "About MD Lite",
        "Un lector Markdown nativo y ligero para macOS.": "A lightweight native Markdown reader for macOS.",
        "Visitar GitHub y dejar una estrella": "Visit GitHub and leave a star",
        "Dejar una estrella en GitHub": "Leave a star on GitHub",
        "Asociar archivos Markdown": "Set as Markdown app",
        "No se pudo asociar Markdown": "Unable to associate Markdown",
        "Pegar y leer": "Paste and Read",
        "Pega o escribe tu Markdown aquí.": "Paste or type your Markdown here.",
        "Vista de lectura": "Reading View",
        "Cancelar": "Cancel",
        "Este texto es temporal y no se guarda al cerrar la app.": "This text is temporary and is not saved when you close the app.",
        "Preferencias": "Preferences",

        "Abrir Markdown…": "Open Markdown…",
        "Abrir reciente": "Open Recent",
        "Buscar en el documento": "Find in Document",
        "Lectura": "Reading",
        "Salir del modo enfoque": "Exit Focus Mode",
        "Modo enfoque": "Focus Mode",
        "Ver código fuente": "Show Source",
        "Aumentar texto": "Increase Text Size",
        "Reducir texto": "Decrease Text Size",
        "Tamaño original": "Actual Size",
        "Actualizar": "Reload",
        "No se pudo leer el archivo": "Unable to Read File",
        "Entendido": "OK",
        "ESPACIO PARA LEER": "A LITTLE SPACE TO READ",
        "Abrir documento": "Open Document",
        "DOCUMENTO": "DOCUMENT",
        "Bienvenido": "Welcome",
        "EN ESTA PÁGINA": "ON THIS PAGE",
        "Los títulos aparecerán aquí.": "Headings will appear here.",
        "RECIENTES": "RECENT",
        "LOCAL. SIMPLE. TUYO.": "LOCAL. SIMPLE. YOURS.",
        "Mostrar barra lateral": "Show Sidebar",
        "Buscar · ⌘F": "Find · ⌘F",
        "Ver código fuente · ⇧⌘S": "Show Source · ⇧⌘S",
        "Apariencia": "Appearance",
        "Sistema": "System",
        "Claro": "Light",
        "Oscuro": "Dark",
        "Tipografía y apariencia": "Reading Preferences",
        "CÓDIGO FUENTE": "SOURCE",
        "MARKDOWN": "MARKDOWN",
        "Idioma": "Language",
        "Color de acento": "Accent Color",
        "palabras": "words",
        "min de lectura": "min read",
        "Verde agua": "Teal",
        "Azul": "Blue",
        "Violeta": "Purple",
        "Rosa": "Pink",
        "Naranja": "Orange",
        "Verde": "Green",
        "No se pudo abrir": "Unable to open",
        "No se pudo actualizar el documento.": "Unable to refresh the document.",
        "Elige un archivo de texto UTF-8 de hasta 5 MB.": "Choose a UTF-8 text file no larger than 5 MB.",
        "Imagen": "Image",
        "abrir imagen": "open image",

        "Nueva ventana": "New Window",
        "o elige qué abrir en esta pestaña.": "or choose what to open in this tab.",
        "Cerrar panel": "Close Pane",
        "Pestañas": "Tabs",
        "Cerrar panel: sus pestañas pasan al otro": "Close pane: its tabs move to the other one",
        "Pestaña siguiente": "Show Next Tab",
        "Pestaña anterior": "Show Previous Tab",
        "Mover al panel izquierdo": "Move to Left Pane",
        "Mover al panel derecho": "Move to Right Pane",
        "Abrir a la izquierda": "Open on the left",
        "Abrir a la derecha": "Open on the right",
        "Abrir aquí en una pestaña": "Open here in a tab",
        "Abrir en una pestaña nueva": "Open in New Tab",
        "Cerrar las demás": "Close Other Tabs",
        "Mostrar en Finder": "Show in Finder",
        "Copiar ruta": "Copy Path",
        "Añadir a favoritos": "Add to Favorites",
        "Quitar de favoritos": "Remove from Favorites",
        "FAVORITOS": "FAVORITES",
        "Etiquetas": "Tags",
        "Nueva etiqueta…": "New Tag…",
        "Nueva etiqueta": "New Tag",
        "Nombre de la etiqueta": "Tag name",
        "Añadir": "Add",
        "Quitar todas las etiquetas": "Remove All Tags",
        "Usar como carpeta de trabajo": "Use as Working Folder",
        "Guardar una copia como…": "Save a Copy As…",
        "Duplicar": "Duplicate",
        "Exportar": "Export",
        "HTML…": "HTML…",
        "PDF…": "PDF…",
        "Imprimir…": "Print…",
        "copia": "copy",
        "Salir del enfoque": "Exit Focus",
        "Este documento aún no está guardado.": "This document is not saved yet.",
        "Dividida": "Split",
        "DIVIDIDA": "SPLIT",
        "Nueva pestaña": "New Tab",
        "Abrir carpeta…": "Open Folder…",
        "Abrir carpeta": "Open Folder",
        "Abrir carpeta de trabajo": "Open a working folder",
        "Actualizar carpeta": "Refresh folder",
        "Cerrar carpeta": "Close folder",
        "Sin archivos Markdown": "No Markdown files",
        "⌘-clic para abrir en una pestaña nueva": "⌘-click to open in a new tab",
        "Un pequeño espacio para leer": "A little space to read",
        "Ajustes": "Settings",
        "Bienvenida": "Welcome",
        "Tamaño del texto": "Text Size",
        "%d imágenes remotas bloqueadas para proteger tu privacidad.": "%d remote images blocked to protect your privacy.",
        "Abre tus .md con MD Lite": "Open your .md files with MD Lite",
        "Abre tus archivos .md con MD Lite": "Open your .md files with MD Lite",
        "Abrir": "Open",
        "Abrir enlace en el editor": "Open link in the editor",
        "Advertencia": "Warning",
        "Ahora no": "Not Now",
        "Ahora se abren con: %@": "They currently open with: %@",
        "Alternar lectura y edición": "Toggle Reading and Editing",
        "Ancho": "Wide",
        "Ancho del texto": "Text Width",
        "App para archivos .md": "App for .md files",
        "Archivo": "File",
        "Así, al hacer doble clic en un archivo Markdown en Finder, se abrirá directamente aquí.": "Double-click any Markdown file in Finder and it opens right here.",
        "Atajos": "Shortcuts",
        "Atajos de teclado": "Keyboard Shortcuts",
        "Aumentar / reducir texto": "Increase / decrease text",
        "Bloque de código": "Code Block",
        "Buscar": "Find",
        "Buscar actualizaciones": "Check for Updates",
        "Buscar actualizaciones automáticamente": "Check for updates automatically",
        "Buscar actualizaciones…": "Check for Updates…",
        "Buscar anterior": "Find Previous",
        "Buscar siguiente": "Find Next",
        "Buscar siguiente / anterior": "Find next / previous",
        "Buscar…": "Find…",
        "Cargar siempre imágenes remotas": "Always load remote images",
        "Cerrar": "Close",
        "Cita": "Quote",
        "Columna": "Column",
        "Completo": "Full",
        "Configurar…": "Set Up…",
        "Consejo": "Tip",
        "Continuar lista o cita": "Continue list or quote",
        "Contraer todo": "Collapse All",
        "Copiado": "Copied",
        "Cursiva": "Italic",
        "Código": "Source",
        "Código en línea": "Inline Code",
        "Descargar": "Download",
        "Deshacer": "Undo",
        "Doble clic en Finder y se abren aquí.": "Double-click in Finder to open them here.",
        "EDITOR": "EDITOR",
        "Edición": "Editing",
        "Editor": "Editor",
        "En Finder, selecciona un archivo .md y pulsa ⌘I (Obtener información).": "In Finder, select a .md file and press ⌘I (Get Info).",
        "En “Abrir con”, elige MD Lite.": "Under “Open with”, choose MD Lite.",
        "Enlace": "Link",
        "Especificación GFM": "GFM Specification",
        "Estrecho": "Narrow",
        "Expandir todo": "Expand All",
        "Filtrar títulos": "Filter headings",
        "Formato": "Format",
        "Guardado": "Saved",
        "Guardando…": "Saving…",
        "Guardar": "Save",
        "Guardar como…": "Save As…",
        "Guardar…": "Save…",
        "Guía de Markdown": "Markdown Guide",
        "Haz doble clic en cualquier Markdown en Finder. Puedes cambiarlo cuando quieras.": "Double-click any Markdown file in Finder. You can change this anytime.",
        "Importante": "Important",
        "Informar de un problema": "Report an Issue",
        "LECTURA": "READING",
        "Lista de tareas": "Task List",
        "Lista numerada": "Numbered List",
        "Listo": "Done",
        "Listo. MD Lite ya abre tus archivos .md y .markdown.": "All set. MD Lite now opens your .md and .markdown files.",
        "MD Lite %@ está disponible": "MD Lite %@ is available",
        "MD Lite abre tus .md": "MD Lite opens your .md files",
        "MD Lite está al día": "MD Lite is up to date",
        "Mostrar": "Show",
        "Mostrar u ocultar la barra lateral": "Show or hide the sidebar",
        "Más tarde": "Later",
        "Navegación": "Navigation",
        "No guardar": "Don’t Save",
        "No se pudo buscar actualizaciones": "Unable to check for updates",
        "Normal": "Normal",
        "Nota": "Note",
        "Ocultar barra lateral": "Hide Sidebar",
        "Pegar": "Paste",
        "Pegar Markdown…": "Paste Markdown…",
        "Precaución": "Caution",
        "Prefiero hacerlo a mano": "I’d rather do it manually",
        "Pulsa “Cambiar todo…” y confirma.": "Click “Change All…” and confirm.",
        "Pulsa “Usar MD Lite”.": "Click “Use MD Lite”.",
        "Rehacer": "Redo",
        "Revisa tu conexión e inténtalo de nuevo.": "Check your connection and try again.",
        "Sangrar / quitar sangría": "Indent / outdent",
        "Separador": "Divider",
        "Si no los guardas, se perderán.": "Your changes will be lost if you don’t save them.",
        "Sin guardar · ⌘S": "Unsaved · ⌘S",
        "Sin título": "Untitled",
        "Tachado": "Strikethrough",
        "Texto normal": "Body Text",
        "Tienes la versión %@.": "You have version %@.",
        "Tienes la versión más reciente (%@).": "You have the latest version (%@).",
        "Todo MD Lite, sin soltar el teclado.": "All of MD Lite, without leaving the keyboard.",
        "Título 1": "Heading 1",
        "Título 1, 2, 3": "Heading 1, 2, 3",
        "Título 2": "Heading 2",
        "Título 3": "Heading 3",
        "Título anterior": "Previous Heading",
        "Título siguiente": "Next Heading",
        "Usar MD Lite": "Use MD Lite",
        "Usar MD Lite para abrir .md…": "Use MD Lite for .md Files…",
        "Ver cómo →": "See how →",
        "Ver novedades": "What’s New",
        "Vista": "View",
        "Volver a cargar": "Reload",
        "código": "code",
        "dibujando…": "drawing…",
        "enlace": "link",
        "macOS recordará la elección para .md y .markdown.": "macOS remembers the choice for .md and .markdown.",
        "ninguna app": "no app",
        "texto": "text",
        "¿Descartar tus cambios y volver a cargar el archivo?": "Discard your changes and reload the file?",
        "¿Guardar los cambios de “%@”?": "Save changes to “%@”?",
    ]
}

enum AccentChoice: String, CaseIterable, Identifiable {
    case system, teal, blue, purple, pink, orange, green
    var id: String { rawValue }
    var label: String {
        switch self {
        case .system: return "Sistema"
        case .teal: return "Verde agua"
        case .blue: return "Azul"
        case .purple: return "Violeta"
        case .pink: return "Rosa"
        case .orange: return "Naranja"
        case .green: return "Verde"
        }
    }
    var color: NSColor {
        switch self {
        case .system: return .controlAccentColor
        case .teal: return .systemTeal
        case .blue: return .systemBlue
        case .purple: return .systemPurple
        case .pink: return .systemPink
        case .orange: return .systemOrange
        case .green: return .systemGreen
        }
    }
}
